# Site settings
title: BigThings Team # 团队名
description: BigThings团队——世界的守护者
owner:
  name: BigThings # or company name
  email: 571652571@qq.com
  url: https://bigthing-org.github.io
first_published: 2017 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bigthing-org.github.io" 

# on landing page
# - set the greeting only if you want to display the first green section
greeting:
  title: Hello!
# - title for your blog's featured posts
features-title: Featured
# - displayed at the bottom
closing-head: Thanks for visiting
closing-para: Feel free to contact me with any questions, concerns, or just to say hello.
blog_logo: "/images/logo.png"
# on all pages (and the first three you list display with greeting, if included)
social:
  github: https://github.com/bigthing-org/
  email: /contact/

# if you use this repo's `ruby compose.rb` script to initiate new posts, put the
# command to invoke your editor here.
compose:
  editor: atom
  extension: md

# choose where to put back and next links:
# top, bottom, both, none
navlinks: bottom

# expecting more works? mark your list as in-progress
works_in_progress: yes

# If you have custom extensions, specifically includes/_my/custom.scss,
# set this to yes
custom_extensions: no

# Build settings
permalink: /:categories/:title.html
# permalink: /:title.html
markdown: kramdown
highlighter: rouge
sass:
 style: compressed
exclude: ['stuff.html','site.bat','compose.rb','README.md','Gulpfile.js','package.json','node_modules', 'jspm_packages']
include: ['_pages','.htaccess']
defaults:
  - scope:
      path: _pages
    values:
      layout: page
  - scope:
      path: _posts
    values:
      layout: post
  - scope:
      path: _drafts
    values:
      layout: post

# to initialize arrays in assignments (assign myarr = site.empty_array)
# (easier to grok than assign myarr = '' | split',')
empty_array: []
